# Generated by Django 2.2.3 on 2019-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formdata_userformmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='form_fields',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
