# Generated by Django 2.2.3 on 2019-11-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20191107_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='form_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
