# Generated by Django 2.2.1 on 2019-11-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20191107_0836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formdata',
            unique_together=set(),
        ),
    ]
