# Generated by Django 2.2.3 on 2019-11-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20191107_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userformmapping',
            options={'ordering': ['last_updated_on']},
        ),
        migrations.AlterUniqueTogether(
            name='formdata',
            unique_together=set(),
        ),
    ]
