# Generated by Django 2.2.3 on 2019-11-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20191115_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userformmapping',
            options={'ordering': ['-last_updated_on']},
        ),
    ]
