# Generated by Django 2.2.1 on 2019-11-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20191115_0728'),
        ('forms', '0005_auto_20191116_1303'),
    ]

    operations = [
    ]
