# Generated by Django 2.2.1 on 2019-10-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='profile_pic',
            field=models.FileField(default=None, upload_to='profile_pictures/'),
        ),
    ]
