# Generated by Django 2.2.1 on 2019-10-23 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teams_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=255)),
                ('meta_value', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Teams')),
            ],
            options={
                'db_table': 'team_meta',
                'unique_together': {('team', 'meta_key')},
            },
        ),
    ]
