# Generated by Django 2.2.1 on 2019-10-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191028_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='profile_pic',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
