# Generated by Django 2.2.3 on 2019-10-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191028_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(default=None, upload_to='profile_pictures/users/'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='profile_pic',
            field=models.FileField(default=None, upload_to='profile_pictures/teams/'),
        ),
    ]
