# Generated by Django 2.2.1 on 2019-10-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191030_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='profile_pic',
            field=models.FileField(default=None, upload_to='profile_pictures/teams/'),
        ),
    ]
