# Generated by Django 2.2.3 on 2019-10-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191029_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(default='', upload_to='profile_pictures/users/'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='profile_pic',
            field=models.FileField(default='', upload_to='profile_pictures/teams/'),
        ),
    ]
