# Generated by Django 2.2.3 on 2019-10-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191029_1728'),
        ('users', '0006_auto_20191030_1241'),
    ]

    operations = [
    ]
