# Generated by Django 2.2.3 on 2019-11-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20191031_0811'),
        ('users', '0007_merge_20191031_0923'),
    ]

    operations = [
    ]
