# Generated by Django 2.2.1 on 2019-11-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20191104_0907'),
        ('users', '0008_merge_20191105_0843'),
    ]

    operations = [
    ]
