# Generated by Django 2.2.3 on 2019-11-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20191104_0907'),
        ('users', '0008_merge_20191105_0843'),
    ]

    operations = [
    ]
