# Generated by Django 2.2.1 on 2019-11-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20191106_0718'),
        ('users', '0009_merge_20191105_1549'),
    ]

    operations = [
    ]
