# Generated by Django 2.2.1 on 2019-11-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20191107_0313'),
        ('users', '0010_merge_20191107_1255'),
    ]

    operations = [
    ]
