# Generated by Django 2.2.1 on 2019-11-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20191112_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='flag_view_as_team',
            field=models.BooleanField(default=False),
        ),
    ]
