# Generated by Django 2.2.1 on 2019-11-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_flag_view_as_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='flag_view_as_team',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='flag_view_as_team',
            field=models.BooleanField(default=False),
        ),
    ]
