# Generated by Django 2.2.3 on 2019-11-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_clientusermapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['start_time']},
        ),
    ]
